### PR TITLE
fixed import statements

### PR DESCRIPTION
**Pull request by nikasakandelidze**
For me this solved the issue with imports regarding [Issue](https://github.com/dudupopkhadze/typescript-lox-interpreter/issues/2).
I'm quite sure that some why existing imports worked for you locally. Couldn't yet determine why case sensitiveness/insensitiveness might be a problem during imports.

### CODE REVIEW

**Comment by nikasakandelidze** [comment]
As it turns out typescript compiler has next flag: https://www.typescriptlang.org/tsconfig#forceConsistentCasingInFileNames
Which you have already set to True. So it means that all the case-s for imports **MUST** be preserved.

**Review by dudupopkhadze — APPROVED** [review]
LGTM

**Comment by nikasakandelidze** [comment]
I don't have privileges to merge.
Please feel free to do it whenever you feel like it:)

**Comment by dudupopkhadze** [comment]
Fixed in #4

**Pull request closed without merging**
